name: Build and Deploy React App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: |
          pwd
          ls -lart
          npm run build

      - name: Deploy to gh-pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: ./build
          token: ${{ secrets.GH_PAT }}

